[programs.localnet]
solana_state_app = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/sergi/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
